propertyRating/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
    resources :properties do
        resources :reviews do
            resources :comments
        end
    end
  root controller: 'home', action: 'index'
  
  get 'home/about'

end

propertyRating/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
end

propertyRating/app/models/property.rb
class Property < ActiveRecord::Base
    has_many :reviews, :dependent => :destroy
  
  def self.searchAddress(search)
    where("lower(address) LIKE ?", "%#{search.downcase}%")
  end
  
  def self.searchCity(search)
    where("lower(city) LIKE ?", "%#{search.downcase}%")
  end
  
  def self.searchZip(search)
    where("zip LIKE ?", "%#{search}%") 
  end
  
  def average_rating
    return 0 if self.reviews.empty?
    ratings = self.reviews.map{|review| review.rating}
    ratings.reduce{|sum, rating| sum + rating}.to_f / ratings.length
  end
  
   def full_address
     full_address = "#{address} Apt:#{apt} #{city} #{state} #{zip}"
   end
  def star_array
    stars = []
  end
  validates_uniqueness_of :address, :scope => :apt
end

propertyRating/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :property
  has_many :comments, :dependent => :destroy
  validates_presence_of :rating, :explanation
end

propertyRating/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
  end
end

propertyRating/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  after_filter :store_location

  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end
end

propertyRating/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

propertyRating/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :findProperty
    
    def create
        @review = @property.reviews.find(params[:review_id])
        @comment = @review.comments.create(params.require(:comment).permit!)
        redirect_to :back
    end
    
    def show
        @comment = @review.comments.find(params[:id])
    end
    
    def findProperty
        @property = Property.find(params[:property_id])
    end
end

propertyRating/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.select(:address, :apt)
    @properties = Property.joins(:reviews).order("reviews.created_at DESC").group("properties.address").limit(10)
    @properties.last 
  end
  
  def about
  end
  
end

propertyRating/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    if params[:search]
      if params[:search_criteria] == "address"
        @properties = Property.searchAddress(params[:search]).order("created_at DESC")
      elsif params[:search_criteria] == "city"
        @properties = Property.searchCity(params[:search]).order("created_at DESC")
      elsif params[:search_criteria] == "zip"
        @properties = Property.searchZip(params[:search]).order("created_at DESC")
      end
    else
    @properties = Property.all.order('created_at DESC')
    end
  end
 
  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    flash[:notice] = ""
    
    AddressValidator.configure do |config|
          config.key = 'FCED759B3311FF22'
          config.username = 'admin'
          config.password = 'admin'
        end

        addressToCheck = AddressValidator::Address.new(
          name: 'John Doe', #The UPS API requires a name attribute
          street1: @property.address,
          city: @property.city,
          state: @property.state,
          zip: @property.zip,
          country: 'US'
        )

        validator = AddressValidator::Validator.new
        response = validator.validate(addressToCheck)

      if response.valid?
        respond_to do |format|
          if @property.save
            format.html { redirect_to @property, notice: 'Thank you! Your property was successfully added.' }
            format.json { render :show, status: :created, location: @property }
          else
            format.html { render :new }
            format.json { render json: @property.errors, status: :unprocessable_entity }
          end
        end
      elsif response.ambiguous?
        flash[:notice] = "Sorry, that address is too ambiguous. Please try again."
        redirect_to :back
      elsif response.no_canidates?
        flash[:notice] = "Sorry, that address is not valid. Please try again."
        redirect_to :back
      end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:address, :apt, :city, :state, :zip)
    end
end

propertyRating/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :findProperty
    before_action :authenticate_user!, :except => [:index, :show]
    
    def create
        @review = @property.reviews.create(params.require(:review).permit!)
        redirect_to @property
    end
    
    def show
        @review = @property.reviews.find(params[:id])
    end
    
    def destroy
        @review.destroy
        redirect_to @property
    end
    
    def findProperty
        @property = Property.find(params[:property_id])
    end
end

propertyRating/app/helpers/application_helper.rb
module ApplicationHelper
end

propertyRating/app/helpers/comments_helper.rb
module CommentsHelper
end

propertyRating/app/helpers/home_helper.rb
module HomeHelper
end

propertyRating/app/helpers/properties_helper.rb
module PropertiesHelper
end

propertyRating/app/helpers/reviews_helper.rb
module ReviewsHelper
end

propertyRating/app/views/comments/_comment.html.erb
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

Posted <%= time_ago_in_words(comment.created_at) %> ago<br>
<hr>

propertyRating/app/views/comments/_form.html.erb
<%= form_for([@property, @review, @review.comments.build]) do |f| %>
  <div id="text_fields"> 
    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :body, :required => true %>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

propertyRating/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<header id="address_header">
  <%= @property.address %> <%= @property.apt %>
  <br>
  <%= @property.city %> <%= @property.state %> <%= @property.zip %>
</header>

<h2>Reviews</h2>
<%= render @property.reviews.order("created_at desc") %>


<h4>Add a review:</h4>
<%= render "reviews/form" %>

<%= link_to 'Back', properties_path %>

propertyRating/app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

propertyRating/app/views/home/index.html.erb
<title>Property World</title>
<link href="style.css" rel="stylesheet">
<div class="splash">
  <div class="sec1">
    <header>
      <h1>Welcome to Property World</h1>
    </header>
    <!--These are the buttons from the splash page we are taking out for demos until they work.
        There is CSS for this div#hmenu that is also commented out.
    <div id="hmenu">
      <ul>
        <li><a href="signup.html">Rate Property</a></li>
        <li><a href="landLordSU.html">I'm a landlord</a></li>
      </ul>  
    </div> -->
      <%= form_tag(properties_path, :method => "get", id: "search-form") do %>
        <%= label_tag 'Search by:' %>
        <%= select_tag :search_criteria, options_for_select([["Address", "address"], ["City", "city"], ["Zip", "zip"]], params[:search_criteria]) %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Properties" %>
        <%= submit_tag "Search" %>
      <% end %>
      <div class="latest">
        <h3>Most Recently Reviewed Properties</h3>
        <table>
          <thead>
            <tr>
              <th>Address</th>
              <th>Average Rating</th>
            </tr>
          </thead>  
          <tbody>
            <% @properties.each do |property|%>
              
              <tr>
                <td><%= link_to property.full_address, property %></td>
                <td><span id="avg_rating"><%=property.average_rating.round(2)%></span>
                  <% (1 .. property.average_rating).each do%>  
                  <%= image_tag("star_on.png", :alt => "gold star", :class => "star") %>
                  <%end%>
                  <% if (property.average_rating > property.average_rating.floor && property.average_rating < property.average_rating.ceil) %>
                    <%= image_tag("half_star_on.png", :alt => "Half gold star", :class =>"star") %>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> <!-- end of "latest" -->
  </div>  <!-- end of "sec1" -->
</div>  <!-- end of "splash" -->

propertyRating/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyRating</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <nav>
        <div id="login">
          <% if current_user %>
            <%= link_to "Sign out",  destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign in with Facebook", "/users/auth/facebook", id: "sign_in" %>
          <% end %>
        </div>
        <%=link_to 'Home', root_path %>
        |
        <%=link_to link_to 'View All Properties', properties_url %>
      </nav>
      <%= yield %>
    </div> <!-- end of "wrapper" div -->
  </body>
</html>

propertyRating/app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <% @property.errors.full_messages.each do |message| %>
      <h2><%= message %></h2>
      <% end %>
      <ul>
        <li><%=link_to 'Click here to return to homepage to search for the property', controller: 'home', action: 'index' %></li>
      </ul>
    </div>
  <% end %>
  <div id="text_fields">
    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address, :required => true %>
    </div>
    <div class="field">
      <%= f.label :apt %>
      <%= f.text_field :apt %>
    </div>
    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city, :required => true %>
    </div>
    <div class="field">
      <%= f.label :state %>
      <%= f.select :state,[["Wisconsin","WI"]], :required => true%>
    </div>
    <div class="field">
      <%= f.label :zip %>
      <%= f.text_field :zip, :required => true%>
    </div>
    <div class="field">
      <%= f.label :Bedroom_count %>
      <%= f.text_field :rooms%>
    </div>
    <div class="field">
      <%= f.label :Rent %>
      <%= f.text_field :rent%>
    </div>
    <div class="field">
      <%= f.label :Utility_cost %>
      <%= f.text_field :utilities%>
    </div>
  </div>
  <div class="option">
    <%= f.label :Pets_Allowed %>
    <%= radio_button_tag(:pets, "yes") %>
    <%= label_tag(:yes, "Yes") %>
    <%= radio_button_tag(:pets, "no") %>
    <%= label_tag(:no, "No") %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

propertyRating/app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

propertyRating/app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1>Listing Properties</h1>
</header>
<% if @properties.blank? %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
  <p>Click new property to add</p>
<% else %>
  


<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Average Rating</th>
    </tr>
  </thead>

  <tbody id="properties">
    <% @properties.each do |property| %>
      <tr>
        <td><%= link_to property.full_address, property %></td>
        <td><%= property.average_rating.round(2) %>
        <% (1 .. property.average_rating).each do%>  
          <%= image_tag("star_on.png", :alt => "gold star", :class => "star") %>
        <%end%>
        <% if (property.average_rating > property.average_rating.floor && property.average_rating < property.average_rating.ceil) %>
          <%= image_tag("half_star_on.png", :alt => "Half gold star", :class =>"star") %>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>
<%= link_to 'New Property', new_property_path %>

propertyRating/app/views/properties/new.html.erb
<header>
  <h1>New Property</h1>
</header>
<h4 class="notice"><%=flash[:notice]%></h4>

<%= render 'form' %>

<%= link_to 'Cancel', properties_path %>

propertyRating/app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<header id="address_header">
  <%= @property.address %> <%= @property.apt %>
  <br>
  <%= @property.city %> <%= @property.state %> <%= @property.zip %>
</header>

<div id="review_content">
<h2>Reviews</h2>
<%= render @property.reviews.order("created_at desc") %>


<h4>Add a review:</h4>
<%= render "reviews/form" %>

<%= link_to 'Back', properties_path %>
</div>

propertyRating/app/views/reviews/_form.html.erb
<%= form_for([@property, @property.reviews.build]) do |f| %>    

    <div id="review_fields">
        <div class="field">
          <div id="ratings">
            <%= f.label :rating %>
            <%= f.select :rating, [['1',1],['2',2],['3',3],['4',4],['5',5]]  %>
<!--             <ul> Add this back in once able to implement star rating
              <%(1..5).each do |i| %>
              <li class = "rating_star" data-stars= "<%= i %>" data-property-id="<%= @property.id %>" id="<%= "#{@property.id}_#{i}"%>"></li>
              <%end%>
            </ul> -->
          </div>
        </div>
        <div class="field">
          <div id="review">
            <%= f.label :review %>
            <%= f.text_area :explanation, :required => true, :rows =>4 %>
          </div>
        </div>
      </div>
      <br>
      <div id="submit" class="actions">
        <%= f.submit %>
      </div> 
<% end %>

propertyRating/app/views/reviews/_review.html.erb
<p>
  <b>Rating:</b>
  <% (1 .. review.rating).each do%>  
  <%= image_tag("star_on.png", :alt => "gold star", :class => "star") %>
  <%end%>
</p>
 
<p>
  <b>Explanation:</b>
  <%= review.explanation %>
</p>

Posted <%= time_ago_in_words(review.created_at) %> ago<br>

<p>
   <%= link_to 'comments', property_review_path(@property, review) %>
</p>

<hr>

propertyRating/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<header id="address_header">
  Review: <%= @review.explanation %> 
  <br>
  Rating: <%= @review.rating %>
</header>

<p>Do you like this review?</p>

<a href="#like">Like</a>
<a href="#dislike">DisLike</a>
<div id="like">You like this review</div>

<div id="dislike">You don't like this review</div>

<h2>Comments</h2>
<%= render @review.comments.order("created_at desc") %>

<h2>Leave a Comment</h2>
<%= render "comments/form" %>




<%= link_to 'Back', properties_path %>